
export const EVENTCATEGORIES = [
  "Coding Events",
  "Design Events",
  "Marketing Events",
  "Business Events",
  "Tech Events"
]

export const EVENTS = [
  {
    id: 1,
    name: "Python Workshop",
    venue: "Online",
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    coordinators: ["Alice Smith", "Bob Johnson"],
    rules: ["Join 10 minutes early", "Keep your mic muted unless speaking"],
    description: "A comprehensive workshop on Python programming for beginners.",
    img: "carouselEvent.png",
    category: "Coding Events",
  },
  {
    id: 2,
    name: "React Conference",
    venue: "Tech Hub, Downtown",
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    coordinators: ["Charlie Brown", "Diana Prince"],
    rules: ["Registration is mandatory", "Follow the event schedule"],
    description: "An in-depth conference discussing React and its ecosystem.",
    img: "carouselEvent.png",
    category: "Coding Events",
  },
  {
    id: 3,
    name: "UI/UX Workshop",
    venue: "Design Center, City Hall",
    startTime: "11:00 AM",
    endTime: "3:00 PM",
    coordinators: ["Eve Davis", "Frank Moore"],
    rules: ["Bring a sketchbook", "Be prepared to share your designs"],
    description: "Learn the fundamentals of UI/UX design with hands-on activities.",
    img: "carouselEvent.png",
    category: "Design Events",
  },
  {
    id: 4,
    name: "Digital Marketing",
    venue: "Marketing Arena, Block B",
    startTime: "1:00 PM",
    endTime: "4:00 PM",
    coordinators: ["Grace Lee", "Hank Miller"],
    rules: ["Bring your own laptop", "Complete pre-event assignments"],
    description: "Master digital marketing strategies and tools in this interactive session.",
    img: "carouselEvent.png",
    category: "Marketing Events",
  },
  {
    id: 5,
    name: "Startup Summit",
    venue: "Startup Pavilion, Floor 2",
    startTime: "10:00 AM",
    endTime: "6:00 PM",
    coordinators: ["Ivy Scott", "Jake White"],
    rules: ["Business casual attire", "Networking encouraged"],
    description: "A summit to connect startups with investors and industry leaders.",
    img: "carouselEvent.png",
    category: "Business Events",
  },
  {
    id: 6,
    name: "AI Conference",
    venue: "Innovation Center, Hall A",
    startTime: "9:30 AM",
    endTime: "5:30 PM",
    coordinators: ["Kim Lopez", "Liam Green"],
    rules: ["No recordings allowed", "Ask questions during Q&A sessions"],
    description: "Dive into the latest advancements in AI and machine learning.",
    img: "carouselEvent.png",
    category: "Tech Events",
  },
  {
    id: 7,
    name: "Web Development",
    venue: "Dev Hub, Room 101",
    startTime: "10:00 AM",
    endTime: "4:00 PM",
    coordinators: ["Nina Brown", "Oscar King"],
    rules: ["Laptop required", "Install required software beforehand"],
    description: "Explore modern web development practices and tools.",
    img: "carouselEvent.png",
    category: "Coding Events",
  },
  {
    id: 8,
    name: "Brand Strategy",
    venue: "Marketing Hub, Wing C",
    startTime: "2:00 PM",
    endTime: "5:00 PM",
    coordinators: ["Pamela Walker", "Quincy Adams"],
    rules: ["Be ready to present ideas", "Teamwork is encouraged"],
    description: "Learn how to build a strong brand strategy from experts.",
    img: "carouselEvent.png",
    category: "Marketing Events",
  },
  {
    id: 9,
    name: "Mobile Dev Summit",
    venue: "Tech Valley, Room 202",
    startTime: "9:00 AM",
    endTime: "3:00 PM",
    coordinators: ["Rachel Green", "Sam Carter"],
    rules: ["Bring your own device", "Follow workshop instructions"],
    description: "A summit dedicated to mobile app development trends and technologies.",
    img: "carouselEvent.png",
    category: "Tech Events",
  },
];
